[package]
name = "enpass-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
hex = "0.4.3"
pbkdf2 = "0.12.2"
rusqlite = { version = "0.32.1", features = ["sqlcipher"] }
sha2 = "0.10.8"
