[package]
name = "enpass"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["std"] }
hex = "0.4.3"
pbkdf2 = "0.12.2"
rusqlite = { version = "0.32.1", features = ["sqlcipher"] }
sha2 = "0.10.8"
thiserror = "1.0.63"
