name: Cargo vendor
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  vendor:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        toolchain:
          - 1.75.0
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo vendor
      - run: tar -cJf vendor-${{github.ref_name}}.tar.xz vendor/
      - run: gh release upload ${{github.ref_name}} vendor-${{github.ref_name}}.tar.xz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
